In [1]:
import pandas as pd
import matplotlib as mp
import re
import plotly.plotly as py
import plotly.graph_objs as go
import sklearn as sk


In [2]:
df_train = pd.read_csv('Data/train.csv', encoding='ISO-8859-1')
df_attr = pd.read_csv('Data/attributes.csv',  encoding='ISO-8859-1')
df_prod_desc = pd.read_csv('Data/attributes.csv', encoding='ISO-8859-1')

In [3]:
df_attr[df_attr.name.str.contains('.Color.') == True].groupby('value').count()

product_uid  name
value                                                                
.Combination Pack                                             2     2
0                                                            99    99
000                                                           1     1
1                                                             5     5
1800                                                          1     1
2000                                                          2     2
2200                                                         11    11
22000                                                         1     1
2300                                                          1     1
2450                                                          2     2
2500                                                         29    29
2525                                                          1     1
2550                                                          5     5
2600                                                          8     8
2610                                                          1     1
2650                                                          9     9
2700                                                        372   372
2720                                                          1     1
2730                                                          3     3
2740                                                          1     1
2750                                                         11    11
2780                                                          1     1
2790                                                          3     3
2800                                                         34    34
2810                                                          1     1
2850                                                         14    14
2860                                                          4     4
2880                                                          1     1
2900                                                         48    48
2920                                                          3     3
...                                                         ...   ...
muree primrose                                                2     2
oil rubbed bronze                                             2     2
oil rubbed bronze (greenish tints)                            1     1
oil rubbed bronze finish with alabaster glass                 1     1
oil rubbed bronze finish with alabaster glass s...            3     3
oil rubbed bronze finish with alabaster glass s...            1     1
oil rubbed bronze finish with clear glass                     1     1
oil rubbed bronze with alabaster glass shade                  1     1
oiled bronze                                                  3     3
pattern                                                       1     1
polished brass                                                1     1
polished bronze                                               1     1
polished nickel                                               1     1
polished stainless steel                                      1     1
red                                                           2     2
red, green and blue glass                                     1     1
restoration bronze                                            1     1
rust                                                          1     1
sand                                                          1     1
satin nickel finish with alabaster glass                      1     1
satin nickel finish with alabaster glass shade                1     1
satin nickel finish with clear glass                          1     1
satin nickel finish with frosted glass shades                 1     1
silver                                                        3     3
solid                                                         

In [4]:
def getPercStr1inStr2(str1, str2):
    # tokenized_str1 = nltk.tokenize.word_tokenize(str(str1))
    str2 = re.sub(r'[^\x00-\x7F]+',' ', str2)
    tokenized_str1 = str1.split()
    return sum([int(word in str2) for word in tokenized_str1])/float(len(tokenized_str1))

In [5]:
getPercStr1inStr2(df_train['search_term'][0], df_train['product_title'][0])

0.0

In [6]:
df_train['search_in_title'] = list(map(lambda x: getPercStr1inStr2(df_train['search_term'][x], df_train['product_title'][x]), range(df_train.shape[0])))

In [9]:
df_trainedModel = pd.read_table('Data/train_with_features.csv', sep="|", quotechar=" ", encoding='ISO-8859-1')


In [12]:
df_trainedModel.columns

Index(['product_uid', 'id', 'product_title', 'search_term', 'relevance',
       'product_description', 'perc_term_in_title', 'perc_term_in_descr',
       'whole_term_in_title', 'whole_term_in_descr', 'search_term_length'],
      dtype='object')

In [11]:
#Renaming to remove the quotes from the beginning of the col names
df_trainedModel.rename(columns=lambda x: x[:-1], inplace=True)
df_trainedModel.rename(columns=lambda x: x[1:], inplace=True)

In [13]:
df_trainedModel_data = df_trainedModel[['perc_term_in_title','perc_term_in_descr','whole_term_in_title','whole_term_in_descr','search_term_length']]

In [14]:
import math
df_trainedModel_target = df_trainedModel['relevance'].map(lambda x: math.floor(x))

In [16]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
new_model = gnb.fit(df_trainedModel_data, df_trainedModel_target)

In [17]:
y_pred= new_model.predict(df_trainedModel_data)

In [18]:
print("Number of mislabeled points out of a total %d points : %d" % (df_trainedModel_data.shape[0],(df_trainedModel_target != y_pred).sum()))

Number of mislabeled points out of a total 74067 points : 32285


In [34]:
from sklearn.metrics import confusion_matrix
confusion_matrix(df_trainedModel_target, y_pred)

array([[ 2201,  9067,   641],
       [ 3731, 35898,  3404],
       [ 1161, 14281,  3683]])

In [36]:
import numpy as np
from sklearn import cross_validation
train_data, test_data, train_target, test_target = cross_validation.train_test_split \
                    (df_trainedModel_data, df_trainedModel_target, \
                    test_size = 0.3, random_state = 0)

In [37]:
train_data.shape, train_target.shape

((51846, 5), (51846,))

In [39]:
test_data.shape, test_target.shape

((22221, 5), (22221,))

In [40]:
newM = gnb.fit(train_data, train_target)
newM.score(test_data, test_target)

0.56689617928986091

In [45]:
scores = cross_validation.cross_val_score(gnb, df_trainedModel_data, df_trainedModel_target, cv=10)
scores

array([ 0.5537257 ,  0.54846112,  0.5449514 ,  0.54961523,  0.5436749 ,
        0.54847421,  0.54590872,  0.62975965,  0.61139617,  0.56394328])

In [46]:
print("Gaussian Naive Bayes Model using 10 fold CV ")
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Gaussian Naive Bayes Model using 5 fold CV 
Accuracy: 0.56 (+/- 0.06)


In [49]:
from sklearn import metrics
predicted = cross_validation.cross_val_predict(gnb, df_trainedModel_data, df_trainedModel_target, cv=10)
metrics.accuracy_score(df_trainedModel_target, predicted)

0.56398936098397401

In [59]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import log_loss

clf = RandomForestClassifier(n_estimators=100)
clf.fit(train_data, train_target)
clf_probs = clf.predict_proba(test_data)
score = log_loss(test_target, clf_probs)

In [60]:
clf.score(test_data, test_target)

0.59502272624994379

In [62]:
regModel_data = df_trainedModel[['perc_term_in_title','perc_term_in_descr','whole_term_in_title','whole_term_in_descr','search_term_length']]
regModel_target = df_trainedModel['relevance']
rtrain_data, rtest_data, rtrain_target, rtest_target = cross_validation.train_test_split \
                    (regModel_data, regModel_target, \
                    test_size = 0.3, random_state = 0)

In [63]:
rtrain_data.shape, rtrain_target.shape

((51846, 5), (51846,))

In [79]:
from sklearn.ensemble import RandomForestRegressor
clf2 = RandomForestRegressor(n_estimators=100)
clf2.fit(rtrain_data, rtrain_target)
#clf2.score(rtest_data, rtest_target)
predicted = cross_validation.cross_val_predict(clf2, rtrain_data, rtrain_target, cv=10)

In [80]:
predicted

array([ 2.76254589,  2.27770788,  2.55455742, ...,  2.65615442,
        2.30753567,  2.21159133])

In [81]:
metrics.mean_squared_error(rtrain_target, predicted)

0.25629944663868492

In [82]:
predicted = cross_validation.cross_val_predict(clf2, rtest_data, rtest_target, cv=10)

In [83]:
metrics.mean_squared_error(rtest_target, predicted)

0.25717455082128488

In [84]:
rtrain_data

perc_term_in_title  perc_term_in_descr whole_term_in_title  \
"34506"            1.000000            1.000000                True   
"66441"            0.333333            0.333333               False   
"17902"            1.000000            1.000000                True   
"46210"            0.166667            0.333333               False   
"71029"            0.666667            0.666667               False   
"45040"            1.000000            1.000000               False   
"10772"            0.500000            0.750000               False   
"25447"            1.000000            1.000000               False   
"13295"            0.000000            0.000000               False   
"791"              1.000000            1.000000                True   
"35400"            0.333333            1.000000               False   
"19954"            1.000000            0.000000                True   
"58810"            0.400000            0.200000               False   
"36048"            1.000000            1.000000                True   
"30379"            1.000000            1.000000                True   
"39334"            0.600000            0.400000               False   
"13954"            0.000000            0.000000               False   
"8277"             1.000000            1.000000               False   
"4335"             0.333333            0.333333               False   
"26718"            0.000000            0.000000               False   
"9940"             0.500000            1.000000               False   
"42041"            0.000000            0.200000               False   
"49893"            0.200000            0.200000               False   
"37699"            0.666667            0.666667               False   
"70013"            0.250000            0.500000               False   
"39089"            0.000000            1.000000               False   
"4407"             0.333333            0.333333               False   
"1714"             0.250000            0.500000               False   
"73030"            0.200000            0.600000               False   
"62671"            0.000000            0.000000               False   
...                     ...                 ...                 ...   
"41505"            0.500000            0.000000               False   
"52490"            1.000000            1.000000                True   
"68756"            1.000000            1.000000                True   
"49812"            0.600000            0.600000               False   
"798"              0.333333            0.333333               False   
"31922"            0.666667            0.000000               False   
"24676"            0.666667            0.333333               False   
"47955"            1.000000            1.000000                True   
"2497"             1.000000            1.000000                True   
"73136"            0.500000            0.500000               False   
"1872"             1.000000            1.000000                True   
"7878"             0.500000            0.500000               False   
"37620"            1.000000            0.500000               False   
"70609"            0.666667            0.666667               False   
"67700"            0.500000            0.250000               False   
"38805"            0.500000            0.500000               False   
"6922"             0.500000            0.500000               False   
"18984"            0.000000            0.500000               False   
"32231"            0.250000            0.250000               False   
"17090"            0.600000            1.000000               False   
"52621"            0.500000            0.250000               False   
"39513"            0.500000            0.000000               False   
"48601"            0.333333            0.666667               False   
"55027"            0.666667            0.666667               False   
"41994"            0.666667      

In [86]:
df_attr.head()

product_uid      name                                              value
0       100001  Bullet01  Versatile connector for various 90° connectio...
1       100001  Bullet02  Stronger than angled nailing or screw fastenin...
2       100001  Bullet03  Help ensure joints are consistently straight a...
3       100001  Bullet04              Dimensions: 3 in. x 3 in. x 1-1/2 in.
4       100001  Bullet05                           Made from 12-Gauge steel